# Generated by Django 3.2.16 on 2023-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='class_num',
            field=models.CharField(db_column='class_num', default='', max_length=255, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='stu_class',
            field=models.CharField(db_column='stu_class', default='', max_length=255, verbose_name='班级名称'),
        ),
    ]
