# Generated by Django 3.2.16 on 2023-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0002_auto_20230531_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_user',
            name='stu_name',
            field=models.CharField(db_column='stu_name', default='', max_length=255, verbose_name='学生姓名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='stu_name',
            field=models.CharField(db_column='stu_name', default='', max_length=255, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='stu_user',
            name='class_num',
            field=models.CharField(db_column='class_num', default='', max_length=255, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='stu_user',
            name='stu_account',
            field=models.CharField(db_column='stu_account', default='', max_length=255, verbose_name='学生帐号'),
        ),
        migrations.AlterField(
            model_name='stu_user',
            name='stu_class',
            field=models.CharField(db_column='stu_class', default='', max_length=255, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='stu_user',
            name='stu_id',
            field=models.CharField(db_column='stu_id', default='', max_length=255, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='stu_user',
            name='stu_pass',
            field=models.CharField(db_column='stu_pass', default='', max_length=255, verbose_name='密码'),
        ),
    ]
