# Generated by Django 3.2.16 on 2023-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0003_auto_20230531_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_user',
            name='stu_status',
            field=models.CharField(db_column='stu_status', default='已启用', max_length=255, verbose_name='学生状态'),
        ),
    ]
