# Generated by Django 3.2.16 on 2023-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0004_stu_user_stu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lat',
            field=models.FloatField(db_column='lat', default=0, verbose_name='签到纬度'),
        ),
        migrations.AddField(
            model_name='task',
            name='lon',
            field=models.FloatField(db_column='lon', default=0, verbose_name='签到经度'),
        ),
    ]
