# Generated by Django 3.2.16 on 2023-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0005_auto_20230531_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='radius',
            field=models.FloatField(db_column='radius', default=0, verbose_name='签到范围'),
        ),
    ]
