# Generated by Django 3.2.16 on 2023-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0006_task_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_user',
            name='stu_task',
            field=models.TextField(db_column='stu_task', default='', max_length=255, verbose_name='学生已完成任务编号'),
        ),
    ]
