# Generated by Django 3.2.16 on 2023-06-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0007_stu_user_stu_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_user',
            name='stunum',
            field=models.CharField(db_column='stunum', default='', max_length=255, verbose_name='班级序号'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='stunum',
            field=models.CharField(db_column='stunum', default='', max_length=255, verbose_name='班级序号'),
        ),
    ]
