# Generated by Django 3.2.16 on 2023-06-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0008_auto_20230601_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_user',
            name='stu_pass',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_stu',
            field=models.BooleanField(db_column='is_stu', default=1, verbose_name='学生账户判断'),
        ),
    ]
