# Generated by Django 3.2.16 on 2023-06-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0009_auto_20230603_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_stu',
        ),
    ]
