# Generated by Django 3.2.16 on 2023-06-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0011_task_clss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='stu_id',
            field=models.CharField(db_column='stu_id', default='', max_length=255, verbose_name='学号'),
        ),
    ]
