# Generated by Django 3.2.16 on 2023-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0012_userinfo_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-03 10:04:54', verbose_name='任务开始时间'),
        ),
    ]
