# Generated by Django 3.2.16 on 2023-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0013_alter_task_task_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='stu_task',
            field=models.TextField(db_column='stu_task', default='', verbose_name='学生已完成任务编号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-03 18:53:55', verbose_name='任务开始时间'),
        ),
    ]
