# Generated by Django 3.2.16 on 2023-06-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0014_auto_20230603_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-04 00:47:11', verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='stu_num',
            field=models.CharField(db_column='stu_num', default=1, max_length=255, verbose_name='班级人数'),
        ),
    ]
