# Generated by Django 3.2.16 on 2023-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0015_auto_20230604_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='stu_num',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-04 01:55:38', verbose_name='任务开始时间'),
        ),
    ]
