# Generated by Django 3.2.16 on 2023-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0016_auto_20230604_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='describe',
            field=models.TextField(db_column='descibe', default='', verbose_name='作业描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-06 10:23:26', verbose_name='任务开始时间'),
        ),
    ]
