# Generated by Django 3.2.16 on 2023-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0020_alter_task_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-06 11:21:19', verbose_name='任务开始时间'),
        ),
    ]
