# Generated by Django 3.2.16 on 2023-06-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0021_alter_task_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.TextField(db_column='task_file', default='', verbose_name='任务附件地址'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(db_column='task_start', default='2023-06-09 21:21:25', verbose_name='任务开始时间'),
        ),
    ]
